config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'home#top'
  get 'home/policy', to: 'home#policy'
  resources :microposts do
    resources :comments
    resource :likes, only: [:create, :destroy]
  end
  resources :users do
    member do
      get :following, :followers, :prof_detail
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
  validates :content, presence: true
  has_many :notifications
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @micropost = Micropost.find(params[:micropost_id])
    @comment = @micropost.comments.build(comments_params)
    @comment.user_id = current_user.id
    if @comment.save
      @micropost.create_notification_comment(current_user, @comment.id)
      render :index
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      render :index
    end
  end

  private
    def comments_params
      params.require(:comment).permit(:content, :micropost_id, :user_id)
    end
end

app/views/comments/_form.html.slim
= form_with(model: [micropost, comment] ) do |form|
  div
    = form.text_area :content
  .actions
    = form.submit "コメント"

app/views/comments/_index.html.slim
- comments.each do |comment|
  - unless comment.id.nil?
    ul
      li.list-inline-item
        = link_to "#{comment.user.name}", user_path(comment.user.id)
      li.list-inline-item
        | コメント：
        = comment.content
      - if comment.user == current_user
        li.list-inline-item
          = link_to '削除', micropost_comment_path(comment.micropost_id, comment.id), method: :delete, remote: true

app/views/comments/index.js.slim
| $("#comments_area").html("
= j(render 'index', { comments: @comment.micropost.comments })
| ") $("textarea").val('') 