config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'home#top'
  get 'home/policy', to: 'home#policy'
  resources :microposts do
    resources :comments
    resource :likes, only: [:create, :destroy]
  end
  resources :users do
    member do
      get :following, :followers, :prof_detail
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
  counter_culture :micropost
  validates :user_id, presence: true
  validates :micropost_id, presence: true
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    like = current_user.likes.build(micropost_id: params[:micropost_id], user_id: current_user.id)
    like.save
    micropost = Micropost.find(params[:micropost_id])
    micropost.create_notification_like(current_user)
    redirect_back(fallback_location: root_url)
  end

  def destroy
    like = Like.find_by(micropost_id: params[:micropost_id])
    like.destroy
    redirect_back(fallback_location: root_url)
  end
end

app/views/likes/_like.html.slim
div
  span.like
    - if micropost.iine?(current_user)
      = link_to "いーね解除", micropost_likes_path(micropost_id: micropost.id), class: "btn btn-xs btn-default", method: :delete
    - else
      = link_to "いーね", micropost_likes_path(micropost_id: micropost.id), class: "btn btn-xs btn-primary", method: :post

app/views/likes/create.js.slim
| $("#micropost-
= @micropost.id
|  .like").html("
= escape_javascript(render "likes/like", micropost: @micropost)
| "); 

app/views/likes/destroy.js.slim
| $("#micropost-
= @micropost.id
|  .like").html("
= escape_javascript(render "likes/like", micropost: @micropost)
| "); 