config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'home#top'
  get 'home/policy', to: 'home#policy'
  resources :microposts do
    resources :comments
    resource :likes, only: [:create, :destroy]
  end
  resources :users do
    member do
      get :following, :followers, :prof_detail
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index
end

app/views/layouts/_footer.html.slim
footer.nav.navbar-fixed-bottom.navbar-inverse
  .container
    nav
      h2
        = link_to "新規投稿", new_micropost_path, class: "btn btn-lg btn-primary"

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  .container
    - if user_signed_in?
      = link_to "INNSUTAGURAMU", microposts_path, id: "logo"
    - else
      = link_to "INNSUTAGURAMU", root_path, id: "logo"
    nav.nav.navbar-nav.navbar-right
      - if user_signed_in?
        li
          = render 'users/search_form'
        li
          = link_to "ログアウト", destroy_user_session_path, method: :delete
        li
          = link_to "マイページ", user_path(current_user.id)
        li
          = link_to "タイムライン", microposts_path
        li
          = link_to "通知一覧", notifications_path
        li
          = link_to "ユーザー一覧", users_path
      - else
        li
          = link_to "新規登録", new_user_registration_path
        li
          = link_to "ログイン", new_user_session_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = full_title(yield(:title))
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/header'
    p.notice
      = notice
    p.alert
      = alert
    .container
      = yield
    - if user_signed_in?
      = render 'layouts/footer'